name: Build Teli APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27.2.12479018e
      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: Teli-APK
          path: "**/build/outputs/apk/**/*.apk"
